### ISSUE TITLE
Able to dupe book & quill with anti-offhand feature

### ISSUE THREAD

**Issue by Turjoy9** [Baktus79/BookLimiter#1]
**Expected behavior**

When player tries to put a book&quill on off-hand slot in survival it should cancel it and put the book&quill to it's original place.

**Observed/Actual behavior**

When player tries to put a book&quill on off-hand slot in survival, book&quill dupes it self and goes to player inventory while the original one stays with cursor.

**Steps/models to reproduce**

While in survival get a book&quill, open your inventory, select book&quill then spam left click on off-hand slot. It will keep duping book&quill untill player inventory is full.

**Notes**:
Doesn't work on creative.
Doesn't work on signed book.
Works on both 1.16.5 and 1.17.
Works on paper forks as well.

**Paper Version**

1.16.5 Build #778 (final build of 1.16.5)
1.17    Build #63  (latest build of 1.17 when creating this issue)

**Plugin List**

BookLimiter

**More Info**

- [x] Running latest paper build for both 1.16.5 and 1.17 from https://papermc.io/downloads.

- [x] Both Server and plugins config files are on default value.

- [x] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Baktus79** [comment]
[Dupe issue fixed](https://github.com/Baktus79/BookLimiter/commit/ef1cf7e99c9325dbab4b6f8a215a6fac73fc0cb4)
This should now be fixed!
